apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-sc
  name: busybox-sc
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: busybox
    name: busybox-sc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
